### ISSUE TITLE
`createdAt` and `updatedAt`

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/wwcode_api#24]
@timchai @samanthamorco @hbotelloelaine 

Hi! What are the intentions behind `createdAt` and `updatedAt` in the models? example: https://github.com/WomenWhoCode/wwcode_api/blob/master/db/schema.rb#L28

**Comment by timchai** [comment]
@zassmin If I remember correctly, I think we added those because it didn't show up when accessing the json url.  So we manually added it.  For instance, if you click on the link below, the "createdAt" and "updatedAt" attributes are the ones we created.  I can have them removed if need be.

staging-wwcode-api.herokuapp.com/api/v1/personalization_questions.json

**Comment by zassmin** [comment]
@timchai, how come you needed them to show up?

**Comment by timchai** [comment]
@zassmin Truthfully, we weren't sure if it needed to show up or not.  So we just added it and figured to just remove it if it wasn't needed.

**Comment by zassmin** [comment]
@timchai ahh, make sense, since their isn't a case for them right now, I'm going to create separate issues to remove them. closing this issue for now, thanks!
